create sequence Customer_SEQ start with 1 increment by 50;
create sequence MyEntity_SEQ start with 1 increment by 50;
create sequence PanacheMyEntity_SEQ start with 1 increment by 50;
create sequence t_artists_SEQ start with 1 increment by 50;
create sequence t_publishers_SEQ start with 1 increment by 50;
create table Customer (createdDate timestamp(6) with time zone, id bigint not null, email varchar(255), firstName varchar(255), lastName varchar(255), primary key (id));
create table MyEntity (id bigint not null, field varchar(255), primary key (id));
create table PanacheMyEntity (id bigint not null, field varchar(255), primary key (id));
create table t_artists (createdDate timestamp(6) with time zone, id bigint not null, bio varchar(255), name varchar(255), primary key (id));
create table t_publishers (createdDate timestamp(6) with time zone, id bigint not null, name varchar(255), primary key (id));
