create sequence MyEntity_SEQ start with 1 increment by 50;
create sequence PanacheMyEntity_SEQ start with 1 increment by 50;
create sequence t_artists_SEQ start with 1 increment by 50;
create sequence t_customers_SEQ start with 1 increment by 50;
create sequence t_items_SEQ start with 1 increment by 50;
create sequence t_publishers_SEQ start with 1 increment by 50;
create table Book (nb_of_pages integer, publication_date date, id bigint not null, isbn varchar(15), language varchar(255) check ((language in ('ENGLISH','FRENCH','SPANISH','PORTUGUESE'))), primary key (id));
create table CD (id bigint not null, genre varchar(100), music_company varchar(255), primary key (id));
create table MyEntity (id bigint not null, field varchar(255), primary key (id));
create table PanacheMyEntity (id bigint not null, field varchar(255), primary key (id));
create table t_artists (created_date timestamp(6) with time zone not null, id bigint not null, name varchar(100) not null, bio varchar(3000), primary key (id));
create table t_customers (created_date timestamp(6) with time zone not null, id bigint not null, first_name varchar(50) not null, last_name varchar(50) not null, e_mail varchar(255) not null, primary key (id));
create table t_items (price numeric(38,2) not null, created_date timestamp(6) with time zone not null, id bigint not null, name varchar(100) not null, description varchar(3000), primary key (id));
create table t_publishers (created_date timestamp(6) with time zone not null, id bigint not null, name varchar(50) not null, primary key (id));
alter table if exists Book add constraint FKrc4aujt4u7vihi7kovrbbtxsv foreign key (id) references t_items;
alter table if exists CD add constraint FKaytv0uvt7n00ea6i2dnw4o78v foreign key (id) references t_items;
