services:
  vintagestore_database:
    image: postgres:17
    container_name: vintagestore_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vintageuser
      POSTGRES_PASSWORD: vinatgepwd
      POSTGRES_DB: vintagestore_database
